### ISSUE TITLE
Unable to build guides

### ISSUE THREAD

**Issue by jaredonline** [hhvm/user-documentation#69]
Hey all, been trying to get the guide to build locally but haven't been able to.

```
2015-11-12 22:12:56] Build sources for /Users/jmcfarland/code/hack/user-documentation/build/systemlib............
Fatal error: Uncaught exception 'HH\InvariantException' with message 'expected type constraint at line 8' in /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/GenericsConsumer.php:87
Stack trace:
#0 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/GenericsConsumer.php(87): HH\invariant_violation()
#1 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ClassConsumer.php(45): FredEmmott\DefinitionFinder\GenericsConsumer->getGenerics()
#2 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(158): FredEmmott\DefinitionFinder\ClassConsumer->getBuilder()
#3 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(126): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#4 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/NamespaceConsumer.php(32): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#5 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(151): FredEmmott\DefinitionFinder\NamespaceConsumer->getBuilder()
#6 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php(126): FredEmmott\DefinitionFinder\ScopeConsumer->consumeDefinition()
#7 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(11): FredEmmott\DefinitionFinder\ScopeConsumer->getBuilder()
#8 /Users/jmcfarland/code/hack/user-documentation/vendor/fredemmott/definition-finder/src/FileParser.php(31): FredEmmott\DefinitionFinder\FileParser->__construct()
#9 /Users/jmcfarland/code/hack/user-documentation/src/build/RawYAMLBuildStep.php(41): FredEmmott\DefinitionFinder\FileParser::FromData()
#10 /Users/jmcfarland/code/hack/user-documentation/src/build/RawYAMLBuildStep.php(15): HHVM\UserDocumentation\RawYAMLBuildStep->buildSources()
#11 /Users/jmcfarland/code/hack/user-documentation/bin/build.php(6): HHVM\UserDocumentation\RawYAMLBuildStep->buildAll()
#12 /Users/jmcfarland/code/hack/user-documentation/bin/build.php(14): HHVM\UserDocumentation\hhvm_to_yaml()
#13 {main}
```

It gets through a few steps before hitting this. I have the `master` branch checked out, going to try it with the `HHVM-3.10` branch.

**Comment by JoelMarcey** [comment]
@jaredonline Did you update composer? Some changes might have been made since last you built.

https://github.com/hhvm/user-documentation#php-dependencies-composer

```
hhvm composer install
```

**Comment by jaredonline** [comment]
@JoelMarcey I pulled the latest changes into my branch and now I'm getting:

```
jmcfarland@Jareds-MacBook-Pro ~/code/hack/user-documentation(search-bar)$ hhvm bin/build.php

Catchable fatal error: Hack type error: Name already bound: Hack\UserDocumentation\Async\Extensions\Examples\MySQL\get_connection at /Users/jmcfarland/code/hack/user-documentation/guides/hack/22-async/08-examples-examples/async-mysql.php line 9
```

**Comment by jaredonline** [comment]
If it helps, here's the output of hh_client:

```
jmcfarland@Jareds-MacBook-Pro ~/code/hack/user-documentation(master)$ hh_client
guides/hack/22-async/08-examples-examples/async-mysql.php:9:16,29: Name already bound: Hack\UserDocumentation\Async\Extensions\Examples\MySQL\get_connection (Naming[2012])
  guides/hack/22-async/06-extensions-examples/async-mysql.php:9:16,29: Previous definition is here
guides/hack/22-async/08-examples-examples/async-mysql.php:22:16,30: Name already bound: Hack\UserDocumentation\Async\Extensions\Examples\MySQL\fetch_user_name (Naming[2012])
  guides/hack/22-async/06-extensions-examples/async-mysql.php:22:16,30: Previous definition is here
guides/hack/22-async/08-examples-examples/async-mysql.php:37:16,28: Name already bound: Hack\UserDocumentation\Async\Extensions\Examples\MySQL\get_user_info (Naming[2012])
  guides/hack/22-async/06-extensions-examples/async-mysql.php:37:16,28: Previous definition is here
guides/hack/22-async/08-examples-examples/async-mysql.php:49:16,35: Name already bound: Hack\UserDocumentation\Async\Extensions\Examples\MySQL\async_mysql_tutorial (Naming[2012])
  guides/hack/22-async/06-extensions-examples/async-mysql.php:49:16,35: Previous definition is here
guides/hack/22-async/08-examples-examples/batching.php:8:16,20: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\Batching\b_one (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/batching.php:8:16,20: Previous definition is here
guides/hack/22-async/08-examples-examples/batching.php:13:16,20: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\Batching\b_two (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/batching.php:13:16,20: Previous definition is here
guides/hack/22-async/08-examples-examples/batching.php:17:16,23: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\Batching\batching (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/batching.php:17:16,23: Previous definition is here
guides/hack/22-async/08-examples-examples/batching.php:25:7,13: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\Batching\Batcher (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/batching.php:25:7,13: Previous definition is here
guides/hack/22-async/08-examples-examples/batching.php:53:16,31: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\Batching\multi_key_lookup (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/batching.php:53:16,31: Previous definition is here
guides/hack/22-async/08-examples-examples/data-dependencies.php:8:7,14: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\DataDependencies\PostData (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/data-dependencies.php:8:7,14: Previous definition is here
guides/hack/22-async/08-examples-examples/data-dependencies.php:13:16,44: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\DataDependencies\fetch_all_post_ids_for_author (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/data-dependencies.php:13:16,44: Previous definition is here
guides/hack/22-async/08-examples-examples/data-dependencies.php:20:16,30: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\DataDependencies\fetch_post_data (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/data-dependencies.php:20:16,30: Previous definition is here
guides/hack/22-async/08-examples-examples/data-dependencies.php:25:16,34: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\DataDependencies\fetch_comment_count (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/data-dependencies.php:25:16,34: Previous definition is here
guides/hack/22-async/08-examples-examples/data-dependencies.php:30:16,30: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\DataDependencies\fetch_page_data (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/data-dependencies.php:30:16,30: Previous definition is here
guides/hack/22-async/08-examples-examples/data-dependencies.php:68:16,28: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\DataDependencies\generate_page (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/data-dependencies.php:68:16,28: Previous definition is here
guides/hack/22-async/08-examples-examples/join.php:5:16,25: Name already bound: Hack\UserDocumentation\Async\Guidelines\Examples\Join\join_async (Naming[2012])
  guides/hack/22-async/07-guidelines-examples/join.php:5:16,25: Previous definition is here
src/api-gen/FunctionMarkdownBuilder.php:151:26,29: Could not find class constant ROOT in type HHVM\UserDocumentation\LocalConfig (Typing[4090])
  LocalConfig.php:5:22,32: Declaration of HHVM\UserDocumentation\LocalConfig is here
```

**Comment by fredemmott** [comment]
- we develop against 3.10 as it's what we deploy with
 - does your LocalConfig.php have ROOT defined? This was added to LocalConfig.php.example ~ a week ago
 - how recent is your master build of HHVM? It worked cleanly with master yesterday, it's possible that HHVM's regressed

I'll try reproing, but assuming it's not a cascading failing from LocalConfig, this is likely to be a typechecker bug not a bug with this site - either way it'll need fixing before 3.11

**Comment by jaredonline** [comment]
@fredemmott here's my LocalConfig.php:

```php
<?hh // strict

namespace HHVM\UserDocumentation;

abstract final class LocalConfig {
  const string ROOT = __DIR__;
  const string BUILD_DIR = __DIR__.'/build';
  const string HHVM_TREE = '/Users/jmcfarland/code/hhvm/hhvm';
}
```

This is what I'm using for HHVM:

```
jmcfarland@Jareds-MacBook-Pro ~/code/hack/user-documentation(master)$ hhvm --version
HipHop VM 3.10.1 (rel)
Compiler: 1446671431_N
Repo schema: 5c1659aeabbd36547e28931f8a2b984a39617f42
```

I've checked out the HHVM-3.10 tag in my local HHVM repo and get the same results

**Comment by fredemmott** [comment]
I have no idea what's happening for this one - do you still have it? 

```
src/api-gen/FunctionMarkdownBuilder.php:151:26,29: Could not find class constant ROOT in type HHVM\UserDocumentation\LocalConfig (Typing[4090])
  LocalConfig.php:5:22,32: Declaration of HHVM\UserDocumentation\LocalConfig is here
```

As for the duplicate definitions: they're real because of a symlink. I have no idea why it works for us on LInux - cc @jwatzman 

Trivial test cases also fail for me:

```
fred@hhvm-oss-bench:~/hhtest$ echo '<?hh class Foo {}' > file.php
fred@hhvm-oss-bench:~/hhtest$ ln -s file.php symlink.php
fred@hhvm-oss-bench:~/hhtest$ hh_client
symlink.php:1:12,14: Name already bound: Foo (Naming[2012])
  file.php:1:12,14: Previous definition is here
```

**Comment by fredemmott** [comment]
My smaller test (that does error on linux):

```
fred@hhvm-oss-bench:~/hhtest$ mkdir -p a b
fred@hhvm-oss-bench:~/hhtest$ echo '<?hh class Foo {}' > a/file.php
fred@hhvm-oss-bench:~/hhtest$ ln -s ../a/file.php b/symlink.php
fred@hhvm-oss-bench:~/hhtest$ hh_client
b/symlink.php:1:12,14: Name already bound: Foo (Naming[2012])
  a/file.php:1:12,14: Previous definition is here
```

**Comment by jwatzman** [comment]
OK, it's an issue with incremental mode, which is likely to hit us in www at some point too.

@jaredonline you can temporarily work around this with `hh_client restart`.

@int3 it looks like we do not read through symlinks in the initial startup, but we do in an incremental update. You made some changes to how we start up, with `find` and `watchman`, right? Can you test this modification of @fredemmott's example and look into it?

```sh
$ cd /tmp
$ mkdir foo
$ cd foo
$ touch .hhconfig
$ mkdir a b
$ echo '<?hh class Foo {}' > a/file.php
$ ln -s ../a/file.php b/symlink.php
$ hh_client
For more detailed logs, try `tail -f $(hh_client --logname)`
Server launched with the following command:
        '/data/users/jwatzman/fbsource/fbcode/_build/dbg/hphp/hack/src/hh_server' '-d' '/tmp/foo' '--waiting-client' '7'
Spawned hh_server (child pid=2090684)
Logs will go to /tmp/hh_server/zStmpzSfoo.log
No errors!
$ hh_client stop
Attempting to nicely kill server for /tmp/foo
Successfully killed server for /tmp/foo
$ rm b/symlink.php 
$ hh_client
For more detailed logs, try `tail -f $(hh_client --logname)`
Server launched with the following command:
        '/data/users/jwatzman/fbsource/fbcode/_build/dbg/hphp/hack/src/hh_server' '-d' '/tmp/foo' '--waiting-client' '7'
Spawned hh_server (child pid=2091276)
Logs will go to /tmp/hh_server/zStmpzSfoo.log
No errors!
$ ln -s ../a/file.php b/symlink.php
$ hh_client
b/symlink.php:1:12,14: Name already bound: Foo (Naming[2012])
  a/file.php:1:12,14: Previous definition is here
```

**Comment by fredemmott** [comment]
filed facebook/hhvm#6551 for the typechecker bug as it's not a documentation issue. Will close this one if hh_client restart works for Jared.

**Comment by jaredonline** [comment]
Looks like `hh_client` worked! I'll re-open if things change.

**Comment by jaredonline** [comment]
After merging the latest upstream I'm now getting this error when I attempt to rebuild:

```
2015-11-19 12:27:33] Finding sources in /Users/jmcfarland/code/hack/user-documentation/build/systemlib-yaml....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Fatal error: Class undefined: HHVM\UserDocumentation\GuidesIndexBuildStep in /Users/jmcfarland/code/hack/user-documentation/bin/build.php on line 9
```

**Comment by daviddoran** [comment]
Make sure to run `composer update`, e.g.

    hhvm /usr/local/bin/composer update

**Comment by jaredonline** [comment]
D'oh. Thanks @daviddoran
