### ISSUE TITLE
Class undefined: AsyncMysqlConnectionPool ?

### ISSUE THREAD

**Issue by integrater** [hhvm/user-documentation#433]
After I update my Ubutnu OS to 17.04 , my Hack project isnt working. Ubuntu asked me to reinstall hhvm. I did that , but now i recive error that AsyncMysqlConnectionPool class is undefined , everything else works fine ... ?

 - Build ID: 2017-04-13T17:22:59+0000:1f7f374ac3d8d9c810df6cf46a63873345f6ed14:c4e655476174fc7cd467ece4b54bb3f9b58025cd
 - Page requested: /hhvm/
 - Page requested at: Fri, 05 May 2017 14:27:05 +0000
 - Controller: GuidesListController

**Comment by mofarrell** [comment]
We don't officially support 17.04 yet.  Did you build from source?  The mysql extension can be disabled in a build.

**Comment by Orvid** [comment]
@aorenste Time to add a package for 17.04 :) Should be much easier this time around.

**Comment by integrater** [comment]
i must reinstall whole system :)
